-- AlterEnum UserRole
ALTER TYPE "UserRole" ADD VALUE IF NOT EXISTS 'PUBLISHER';
ALTER TYPE "UserRole" ADD VALUE IF NOT EXISTS 'MANAGING_DIRECTOR';

-- AlterEnum WebhookProvider
ALTER TYPE "WebhookProvider" ADD VALUE IF NOT EXISTS 'BALE';
ALTER TYPE "WebhookProvider" ADD VALUE IF NOT EXISTS 'SLACK';
ALTER TYPE "WebhookProvider" ADD VALUE IF NOT EXISTS 'DISCORD';
