/** Client-safe enum re-exports (explicit names — no `export *`). */
export {
  UserRole,
  UserStatus,
  ArticleStatus,
  WorkflowStage,
  IssueStatus,
  SubscriptionStatus,
  PaymentStatus,
  PaymentType,
  DiscountCodeType,
  DiscountCodeScope,
  MessageType,
  MessageStatus,
  TaskStatus,
  ContributorType,
  AdCampaignStatus,
  AuditAction,
  TicketStatus,
  TicketCustomerType,
  TicketPriority,
  CommissionStatus,
  NotificationChannel,
  NotificationStatus,
  WebhookProvider,
  ReminderType,
  BulkCampaignStatus,
  NewsletterStatus,
  BackgroundJobStatus,
  DataDeletionStatus,
  CommentStatus,
  ChatConversationStatus,
  ChatSenderType,
} from '@prisma/client';

export type {
  UserRole as UserRoleEnum,
  UserStatus as UserStatusEnum,
  ArticleStatus as ArticleStatusEnum,
  WorkflowStage as WorkflowStageEnum,
  IssueStatus as IssueStatusEnum,
  SubscriptionStatus as SubscriptionStatusEnum,
  PaymentStatus as PaymentStatusEnum,
  PaymentType as PaymentTypeEnum,
  DiscountCodeType as DiscountCodeTypeEnum,
  DiscountCodeScope as DiscountCodeScopeEnum,
  MessageType as MessageTypeEnum,
  MessageStatus as MessageStatusEnum,
  TaskStatus as TaskStatusEnum,
  ContributorType as ContributorTypeEnum,
  AdCampaignStatus as AdCampaignStatusEnum,
  AuditAction as AuditActionEnum,
  TicketStatus as TicketStatusEnum,
  TicketCustomerType as TicketCustomerTypeEnum,
  TicketPriority as TicketPriorityEnum,
  CommissionStatus as CommissionStatusEnum,
  NotificationChannel as NotificationChannelEnum,
  NotificationStatus as NotificationStatusEnum,
  WebhookProvider as WebhookProviderEnum,
  ReminderType as ReminderTypeEnum,
  BulkCampaignStatus as BulkCampaignStatusEnum,
  NewsletterStatus as NewsletterStatusEnum,
  BackgroundJobStatus as BackgroundJobStatusEnum,
  DataDeletionStatus as DataDeletionStatusEnum,
  CommentStatus as CommentStatusEnum,
  ChatConversationStatus as ChatConversationStatusEnum,
  ChatSenderType as ChatSenderTypeEnum,
} from '@prisma/client';
